
//contract-card
var contract =            '  <div class=" w-30 ba b--black-20 bg-white shadow-1 ma3">';
		    contract = contract + '    <ul class="list pa3  mt0 ">';
		    contract = contract + '      <li class="flex items-center lh-copy tc bb b--black-10">';
		    contract = contract + '          <div class="tc flex-auto">';
		    contract = contract + '            <div><span class="f2 lh-title">ContractName </span><i class="fas fa-sync-alt"></i></div>';
		    contract = contract + '            <div>';
		    contract = contract + '            <span class="f7 blue tl">'+contracts[i].address+'</span>';
		    contract = contract + '          </div>';
		    contract = contract + '          </div>';
		    contract = contract + '      </li>';
		    contract = contract + '      <li class="flex items-center lh-copy pa3 ph0-l bb b--black-10">';
		    contract = contract + '          <div class="pl3 flex-auto">';
		    contract = contract + '            <span class="f3 db black-70">supply</span>';
		    contract = contract + '            <span class="f6 db black-70">function</span>';
		    contract = contract + '          </div>';
		    contract = contract + '          <div>';
		    contract = contract + '            <span class="f6 link blue">30</span>';
		    contract = contract + '          </div>';
		    contract = contract + '      </li>';
		    contract = contract + '    </ul>';
		    contract = contract + '  </div>';
		    contract = contract + '';


//wallet-card
var wallet =         ' <div class="demo-card-wide mdl-card mdl-shadow--2dp" >';
		    wallet = wallet + '    <div class="inner-container">';
		    wallet = wallet + '      <div class="inner-container-layout" id="copyBtn" onclick="util.copyToClipboard(\'' + wallets[i].info.address +'\')" style="font-size:1em; color:gray; padding:15px 5px 2px 13px;">';
		    wallet = wallet + '        <i class="far fa-clone" ></i>';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '      <div class="inner-container-layout mdl-card__supporting-text" id="acount-address" style="width:85%; padding:15px 0px 2px 0px;" >';
		    wallet = wallet + '        ' + wallets[i].info.address + '';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '      <div class="inner-container-layout" style="font-size:1em; color:gray; padding:5px 5px 2px 0px;">';
		    wallet = wallet + '        <i class="fas fa-cog"></i>';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '    <div class="inner-container">';
		    wallet = wallet + '      <div class="inner-container-layout mdl-card__supporting-text" style="width:50%; padding-top:0px; padding-bottom:0px" onclick="window.action.touch(\'' + wallets[i].info.address +'\')">';
		    wallet = wallet + '        <img src=' + wallets[i].view.avatar + ' class="br-100 h4 w4 dib ba b--black-05 pa0">';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '      <div class="inner-container-layout mdl-card__supporting-text" style="width:32%;">';
		    wallet = wallet + '        <h4>' + wallets[i].info.balance.toNumber(); + '</h4>';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '    </div>';
		    wallet = wallet + '    <div class="inner-container" style="height:35px">';
		    wallet = wallet + '      <div class="button-align">';
		    wallet = wallet + '        <div class="inner-container-layout">';
		    wallet = wallet + '          <button class="f6 link dim br3 ba ph3 pv2 mb2 dib navy" style="margin-right:10px;" onclick="window.action.allocateSend(\'' + wallets[i].info.address +'\')" >';
		    wallet = wallet + '            send';
		    wallet = wallet + '          </button>';
		    wallet = wallet + '        </div>';
		    wallet = wallet + '        <div class="inner-container-layout">';
		    wallet = wallet + '          <button class="f6 link dim br3 ba ph3 pv2 mb2 dib navy" style="margin-right:10px;">';
		    wallet = wallet + '            call';
		    wallet = wallet + '          </button>';
		    wallet = wallet + '        </div>';
		    wallet = wallet + '        <div class="inner-container-layout">';
		    wallet = wallet + '          <button class="f6 link dim br3 ba ph3 pv2 mb2 dib navy" style="margin-right:10px;">';
		    wallet = wallet + '            sendTransaction';
		    wallet = wallet + '          </button>';
		    wallet = wallet + '        </div>';
		    wallet = wallet + '      </div>';
		    wallet = wallet + '    </div>';
		    wallet = wallet + '    <div class="inner-container" style="border-top:1px solid rgba(0,0,0,.1); height:40px">';
		    wallet = wallet + '        <div class="inner-container-layout mdl-card__supporting-text" style="width:50%; padding:10px 0px 0px 10px; ">';
		    wallet = wallet + '          <font size="2">Test Token </font>';
		    wallet = wallet + '        </div>';
		    wallet = wallet + '        <div class="inner-container-layout mdl-card__supporting-text" style="padding:10px 0px 0px 10px;">';
		    wallet = wallet + '          <font size="3"> 1,320.123545 </font>';
		    wallet = wallet + '        </div>';
		    wallet = wallet + '    </div>';